from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column,String,create_engine,Integer

base=declarative_base()

class incomeReport(base):
    __tablename__='income'
    PeriodEndingDate=Column(String(255),default=None)
    TotalRevenue = Column(String(255),default=None)
    GrossProfit=Column(String(255),default=None)
    NetNonOperatingInterestIncomeExpense=Column(String(255),default=None)
    TotalExpenses=Column(String(255),default=None)
    CostOfRevenue=Column(String(255),default=None)
    SellingGeneralAndAdministration=Column(String(255),default=None)
    ResearchAndDevelopment=Column(String(255),default=None)
    DepreciationAmortizationDepletion=Column(String(255),default=None)
    OperatingIncome=Column(String(255),default=None)
    OtherIncomeExpense=Column(String(255),default=None)
    PretaxIncome=Column(String(255),default=None)
    TaxProvision=Column(String(255),default=None)
    NetIncome=Column(String(255),default=None)
    NetIncomeCommonStockholders=Column(String(255),default=None)
    NetIncomeIncludingNoncontrollingInterests=Column(String(255),default=None)
    NetIncomeContinuousOperations=Column(String(255),default=None)
    BasicEPS=Column(String(255),default=None)
    DilutedEPS=Column(String(255),default=None)
    DividendPerShare=Column(String(255),default=None)
    InterestIncome=Column(String(255),default=None)
    DepreciationAndAmortization=Column(String(255),default=None)
    InterestExpense=Column(String(255),default=None)
    OperatingRevenue=Column(String(255),default=None)
    OperatingExpense=Column(String(255),default=None)
    InterestIncomeNonOperating=Column(String(255),default=None)
    InterestExpenseNonOperating=Column(String(255),default=None)
    TotalOtherFinanceCost=Column(String(255),default=None)
    OtherNonOperatingIncomeExpenses=Column(String(255),default=None)
    NetInterestIncome=Column(String(255),default=None)
    Amortization=Column(String(255),default=None)
    CurrencyUnit=Column(String(255),default=None)
    AccountingStandards=Column(String(255),default=None)
    AuditorReport=Column(String(255),default=None)
    Company=Column(String(255),default=None)
    Id=Column(Integer,primary_key=True,autoincrement=True)